export const MessageType = {
  PROXY_FETCH: 'PROXY_FETCH',
  EXTRACT_PAGE_CONTENT: 'EXTRACT_PAGE_CONTENT',
  OPEN_SIDE_PANEL: 'OPEN_SIDE_PANEL',
  OPEN_STANDALONE: 'OPEN_STANDALONE',
  SESSION_TOKEN_UPDATE: 'SESSION_TOKEN_UPDATE',
  BACKGROUND_STATE: 'BACKGROUND_STATE',
  KEEPALIVE_PING: 'KEEPALIVE_PING',
  PORT_STREAM_START: 'PORT_STREAM_START',
  PORT_STREAM_CHUNK: 'PORT_STREAM_CHUNK',
  PORT_STREAM_END: 'PORT_STREAM_END',
  PORT_STREAM_ABORT: 'PORT_STREAM_ABORT',
  ADDON_EVENT: 'ADDON_EVENT',
  WORKSPACE_HANDOFF: 'WORKSPACE_HANDOFF',
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
  WORKSPACE_HEARTBEAT: 'WORKSPACE_HEARTBEAT',
} as const;

export type MessageTypeValue = (typeof MessageType)[keyof typeof MessageType];

export const MessageTypeValues = Object.values(MessageType) as MessageTypeValue[];
