// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/icons/icon-role-ai-avatar.png"
    | "/assets/icons/icon-role-ai-error.png"
    | "/assets/icons/icon-role-ai-hello.png"
    | "/assets/icons/icon-role-ai-noinfo.png"
    | "/assets/icons/icon-role-ai-processing.png"
    | "/assets/icons/icon-role-ai-success.png"
    | "/assets/icons/icon-role-ai-syncing.png"
    | "/assets/icons/icon-role-user-avatar.png"
    | "/background.js"
    | "/options.html"
    | "/sidepanel.html"
    | "/standalone.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
