export interface BuiltinPromptTemplate {
  id: string;
  name: string;
  description: string;
  template: string;
  category: string;
  variables: string[];
  scopes?: ('chat' | 'reading' | 'writing' | 'reply')[];
  hidden?: boolean;
  icon?: string;
  order?: number;
}

export const builtinTemplates: BuiltinPromptTemplate[] = [
  {
    id: 'testing',
    name: 'Testing',
    description: 'Quick prompt testing',
    template: 'Test the following input:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['chat', 'reading', 'writing'],
    hidden: false,
    icon: 'star',
    order: 1,
  },
  {
    id: 'explain',
    name: 'Explain',
    description: 'Explain this clearly',
    template: 'Explain the following in simple terms:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['chat', 'reading', 'writing'],
    hidden: false,
    icon: 'book',
    order: 2,
  },
  {
    id: 'summarize',
    name: 'Summarize',
    description: 'Summarize content concisely',
    template: 'Summarize the following:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['chat', 'reading', 'writing'],
    hidden: false,
    icon: 'fileText',
    order: 3,
  },
  {
    id: 'improve-writing',
    name: 'Improve writing',
    description: 'Rewrite the following text, making it more concise and well-written',
    template: 'Rewrite the following text, which will be delimited by triple quotes, to be more concise and well-written while preserving the original meaning: """{{userInput}}""" Provide only the rewritten text as your output, without any quotes or tags. Respond in the same language as the original text.',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'edit',
    order: 4,
  },
  {
    id: 'continue-writing',
    name: 'Continue writing',
    description: 'Continue writing from this point',
    template: 'Continue writing the following text:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'form',
    order: 5,
  },
  {
    id: 'fix-spelling-grammar',
    name: 'Fix spelling & grammar',
    description: 'Correct any spelling or grammatical errors',
    template: 'Fix spelling and grammar errors in the following text:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'checkSquare',
    order: 6,
  },
  {
    id: 'translate',
    name: 'Translate',
    description: 'Translate text into another language',
    template: 'Translate the following text:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['reading', 'writing'],
    hidden: false,
    icon: 'translation',
    order: 7,
  },
  {
    id: 'make-shorter',
    name: 'Make shorter',
    description: 'Shorten the text',
    template: 'Make the following text shorter and more concise:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'lineHeight',
    order: 8,
  },
  {
    id: 'make-longer',
    name: 'Make longer',
    description: 'Expand the text with more detail',
    template: 'Expand the following text with more detail and elaboration:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'lineHeight',
    order: 9,
  },
  {
    id: 'simplify-language',
    name: 'Simplify language',
    description: 'Use simpler words and structure',
    template: 'Simplify the language of the following text to make it easier to understand:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'fontColors',
    order: 10,
  },
  {
    id: 'change-tone',
    name: 'Change tone',
    description: 'Adjust the tone of voice',
    template: 'Change the tone of the following text:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'smile',
    order: 11,
  },
  {
    id: 'outline',
    name: 'Outline...',
    description: 'Generate a structured outline',
    template: 'Create a structured outline for the following content:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'unorderedList',
    order: 12,
  },
  {
    id: 'brainstorm',
    name: 'Brainstorm about...',
    description: 'Generate fresh ideas and concepts',
    template: 'Brainstorm ideas and concepts about:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'bulb',
    order: 13,
  },
  {
    id: 'blog-post',
    name: 'Blog post...',
    description: 'Write a beautiful blog post',
    template: 'Draft a blog post about the following topic:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: false,
    icon: 'form',
    order: 14,
  },
  {
    id: 'paragraph-about',
    name: 'Paragraph about...',
    description: 'Write a paragraph on a topic',
    template: 'Write a detailed paragraph about:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'fileText',
    order: 15,
  },
  {
    id: 'social-media-post',
    name: 'Social media post...',
    description: 'Create an engaging post for social channels',
    template: 'Write an engaging social media post about:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'comment',
    order: 16,
  },
  {
    id: 'press-release',
    name: 'Press release',
    description: 'Draft a formal press release',
    template: 'Draft a press release about the following:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'fileText',
    order: 17,
  },
  {
    id: 'creative-story',
    name: 'Creative story',
    description: 'Flesh out a creative narrative',
    template: 'Write a creative story based on:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'book',
    order: 18,
  },
  {
    id: 'to-do-list',
    name: 'To-do list...',
    description: 'Generate an actionable to-do list',
    template: 'Generate an actionable to-do list for:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'checkSquare',
    order: 19,
  },
  {
    id: 'meeting-agenda',
    name: 'Meeting agenda...',
    description: 'Draft an organized agenda',
    template: 'Create a detailed meeting agenda for:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'calendar',
    order: 20,
  },
  {
    id: 'sales-email',
    name: 'Sales email...',
    description: 'Draft a high-conversion sales copy',
    template: 'Draft a persuasive sales email about:\n\n{{userInput}}',
    category: 'builtin',
    variables: ['userInput'],
    scopes: ['writing'],
    hidden: true,
    icon: 'mail',
    order: 21,
  },
];
