import { theme } from 'antd';
import { NowPilotThemeDefinition } from './types';

export const claudeTheme: NowPilotThemeDefinition = {
  id: 'claude',
  label: 'Claude',
  description: 'Warm writing-focused workspace inspired by modern knowledge work tools.',
  light: {
    algorithm: theme.defaultAlgorithm,
    token: {
      colorPrimary: '#c96442',
      colorInfo: '#c96442',
      colorBgBase: '#faf9f5',
      colorBgContainer: '#f5f4ef',
      colorBgElevated: '#ffffff',
      colorText: '#3d3929',
      colorTextSecondary: '#6e6d68',
      colorBorder: '#dad9d4',
      colorBorderSecondary: '#e5e3dc',
      colorFillSecondary: '#e9e6dc',
      colorFillTertiary: '#ede9de',
      borderRadius: 16,
      borderRadiusLG: 16,
      boxShadow: '0 1px 3px rgba(0,0,0,0.10)',
    },
    components: {
      Button: {
        borderRadius: 16,
        fontWeight: 500,
        colorPrimary: '#c96442',
        colorPrimaryHover: '#b55838',
      },
      Input: {
        borderRadius: 16,
        colorBgContainer: '#f5f4ef',
        colorBorder: '#dad9d4',
      },
      Card: {
        borderRadiusLG: 16,
        colorBgContainer: '#f5f4ef',
        colorBorderSecondary: '#dad9d4',
      },
      Modal: {
        borderRadiusLG: 20,
        colorBgElevated: '#ffffff',
      },
      Dropdown: {
        borderRadiusSM: 12,
        colorBgElevated: '#ffffff',
      },
      Select: {
        borderRadius: 16,
        colorBgContainer: '#f5f4ef',
      },
      Segmented: {
        borderRadius: 16,
        colorBgContainer: '#e9e6dc',
      },
    },
  },
  dark: {
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: '#d97757',
      colorInfo: '#d97757',
      colorBgBase: '#262624',
      colorBgContainer: '#2c2c2b',
      colorBgElevated: '#30302e',
      colorText: '#f1f1ef',
      colorTextSecondary: '#b7b5a9',
      colorBorder: '#3e3e38',
      colorBorderSecondary: '#4a4944',
      colorFillSecondary: '#30302e',
      colorFillTertiary: '#1b1b19',
      borderRadius: 16,
      borderRadiusLG: 16,
      boxShadow: '0 1px 3px rgba(0,0,0,0.15)',
    },
    components: {
      Button: {
        borderRadius: 16,
        fontWeight: 500,
        colorPrimary: '#d97757',
        colorPrimaryHover: '#e08567',
      },
      Input: {
        borderRadius: 16,
        colorBgContainer: '#2c2c2b',
        colorBorder: '#3e3e38',
      },
      Card: {
        borderRadiusLG: 16,
        colorBgContainer: '#2c2c2b',
        colorBorderSecondary: '#3e3e38',
      },
      Modal: {
        borderRadiusLG: 20,
        colorBgElevated: '#30302e',
      },
      Dropdown: {
        borderRadiusSM: 12,
        colorBgElevated: '#30302e',
      },
      Select: {
        borderRadius: 16,
        colorBgContainer: '#2c2c2b',
      },
      Segmented: {
        borderRadius: 16,
        colorBgContainer: '#30302e',
      },
    },
  },
  cssVars: {
    light: {
      '--np-bg': '#faf9f5',
      '--np-fg': '#3d3929',
      '--np-card': '#f5f4ef',
      '--np-card-fg': '#141413',
      '--np-primary': '#c96442',
      '--np-muted': '#ede9de',
      '--np-muted-fg': '#6e6d68',
      '--np-accent': '#c96442',
      '--np-accent-fg': '#ffffff',
      '--np-border': '#dad9d4',
      '--np-input': '#b4b2a7',
      '--np-ring': '#c96442',
      '--np-sidebar': '#f5f4ee',
      '--np-sidebar-fg': '#3d3d3a',
      '--np-radius': '16px',
    },
    dark: {
      '--np-bg': '#262624',
      '--np-fg': '#f1f1ef',
      '--np-card': '#2c2c2b',
      '--np-card-fg': '#faf9f5',
      '--np-primary': '#d97757',
      '--np-muted': '#1b1b19',
      '--np-muted-fg': '#b7b5a9',
      '--np-accent': '#d97757',
      '--np-accent-fg': '#141413',
      '--np-border': '#3e3e38',
      '--np-input': '#52514a',
      '--np-ring': '#d97757',
      '--np-sidebar': '#1f1e1d',
      '--np-sidebar-fg': '#c3c0b6',
      '--np-radius': '16px',
    },
  },
};
