import { theme } from 'antd';
import { NowPilotThemeDefinition } from './types';

export const liquidGlassTheme: NowPilotThemeDefinition = {
  id: 'liquid-glass',
  label: 'Liquid Glass',
  description: 'Soft glass-style workspace theme with large radius, subtle depth, and premium surfaces.',
  light: {
    algorithm: theme.defaultAlgorithm,
    token: {
      colorPrimary: '#297cef',
      colorInfo: '#297cef',
      colorBgBase: '#f4f5f7',
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorText: '#0c121a',
      colorTextSecondary: '#565e69',
      colorBorder: '#dbdee2',
      colorBorderSecondary: '#e2e5e8',
      colorFillSecondary: '#e9ebee',
      colorFillTertiary: '#eceff1',
      borderRadius: 24,
      borderRadiusLG: 24,
      borderRadiusSM: 16,
      borderRadiusXS: 12,
      boxShadow: '0 2px 28px rgba(78, 86, 97, 0.10)',
      boxShadowSecondary: '0 1px 2px rgba(78, 86, 97, 0.08)',
    },
    components: {
      Button: {
        borderRadius: 999,
        primaryShadow: 'none',
        controlHeight: 36,
      },
      Select: {
        borderRadius: 16,
        selectorBg: '#ffffff',
        optionSelectedBg: '#d9e6f9',
        optionSelectedColor: '#002c78',
      },
      Card: {
        borderRadiusLG: 24,
        boxShadow: '0 2px 28px rgba(78, 86, 97, 0.10)',
        colorBorderSecondary: '#dbdee2',
      },
      Input: {
        borderRadiusLG: 24,
        borderRadius: 24,
        activeBorderColor: '#297cef',
        hoverBorderColor: '#297cef',
        colorBgContainer: '#ffffff',
      },
      Tooltip: {
        colorBgElevated: '#ffffff',
        borderRadiusLG: 18,
        boxShadow: '0 2px 28px rgba(78, 86, 97, 0.10)',
      },
      Popover: {
        colorBgElevated: '#ffffff',
        borderRadiusLG: 18,
        boxShadow: '0 2px 28px rgba(78, 86, 97, 0.10)',
      },
      Dropdown: {
        colorBgElevated: '#ffffff',
        borderRadiusLG: 18,
        boxShadow: '0 2px 28px rgba(78, 86, 97, 0.10)',
      },
    },
  },
  dark: {
    algorithm: theme.darkAlgorithm,
    token: {
      colorPrimary: '#3a8cff',
      colorInfo: '#3a8cff',
      colorBgBase: '#090b0f',
      colorBgContainer: '#13161b',
      colorBgElevated: '#1a1d22',
      colorText: '#f0f2f4',
      colorTextSecondary: '#8f9aa4',
      colorBorder: '#26292e',
      colorBorderSecondary: '#212429',
      colorFillSecondary: '#1c2024',
      colorFillTertiary: '#181b1f',
      borderRadius: 24,
      borderRadiusLG: 24,
      borderRadiusSM: 16,
      borderRadiusXS: 12,
      boxShadow: '0 4px 40px rgba(0, 0, 0, 0.45)',
      boxShadowSecondary: '0 1px 2px rgba(0, 0, 0, 0.30)',
    },
    components: {
      Button: {
        borderRadius: 999,
        primaryShadow: 'none',
        controlHeight: 36,
      },
      Select: {
        borderRadius: 16,
        selectorBg: '#13161b',
        optionSelectedBg: '#152946',
        optionSelectedColor: '#a5d0ff',
      },
      Card: {
        borderRadiusLG: 24,
        boxShadow: '0 4px 40px rgba(0, 0, 0, 0.45)',
        colorBorderSecondary: '#26292e',
      },
      Input: {
        borderRadiusLG: 24,
        borderRadius: 24,
        activeBorderColor: '#3a8cff',
        hoverBorderColor: '#3a8cff',
        colorBgContainer: '#13161b',
      },
      Tooltip: {
        colorBgElevated: '#1a1d22',
        borderRadiusLG: 18,
        boxShadow: '0 4px 40px rgba(0, 0, 0, 0.45)',
      },
      Popover: {
        colorBgElevated: '#1a1d22',
        borderRadiusLG: 18,
        boxShadow: '0 4px 40px rgba(0, 0, 0, 0.45)',
      },
      Dropdown: {
        colorBgElevated: '#1a1d22',
        borderRadiusLG: 18,
        boxShadow: '0 4px 40px rgba(0, 0, 0, 0.45)',
      },
    },
  },
  cssVars: {
    light: {
      '--np-bg': '#f4f5f7',
      '--np-fg': '#0c121a',
      '--np-card': '#ffffff',
      '--np-card-fg': '#0c121a',
      '--np-muted': '#eceff1',
      '--np-muted-fg': '#565e69',
      '--np-accent': '#d9e6f9',
      '--np-accent-fg': '#002c78',
      '--np-border': '#dbdee2',
      '--np-input': '#e2e5e8',
      '--np-ring': '#297cef',
      '--np-sidebar': '#eceff1',
      '--np-sidebar-fg': '#0c121a',
      '--np-radius': '24px',
      '--np-shadow': '0 2px 28px rgba(78, 86, 97, 0.10)',
    },
    dark: {
      '--np-bg': '#090b0f',
      '--np-fg': '#f0f2f4',
      '--np-card': '#13161b',
      '--np-card-fg': '#f0f2f4',
      '--np-muted': '#181b1f',
      '--np-muted-fg': '#8f9aa4',
      '--np-accent': '#152946',
      '--np-accent-fg': '#a5d0ff',
      '--np-border': '#26292e',
      '--np-input': '#26292e',
      '--np-ring': '#3a8cff',
      '--np-sidebar': '#0f1216',
      '--np-sidebar-fg': '#f0f2f4',
      '--np-radius': '24px',
      '--np-shadow': '0 4px 40px rgba(0, 0, 0, 0.45)',
    },
  },
};
