import { PromptItem, PromptCategory } from '../../types';

export const DEFAULT_PROMPTS_LIST: PromptItem[] = [
  // 1. For YouTube (Custom / special)
  {
    id: 'p_youtube',
    title: 'For YouTube',
    content: 'Generate engaging YouTube video titles, description, timestamps, and key highlights for the following content:',
    category: 'Chat/Ask',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Sparkles',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': false,
    },
    isCustom: true,
    order: 1,
  },
  // 2. Summarize (Detail Enhancer)
  {
    id: 'p_summarize_detail',
    title: 'Summarize',
    content: `# Role: Detail Enhancer You are a highly skilled AI trained in language understanding and detail enhancement. You will read the original text and add some details to make it more believable. ## Rules - Retain the original meaning and structure. - Enhance the text with additional details to make it more believable. - Only provide the output and nothing else. - Do not wrap responses in quotes. - Respond in the same language as the original text. # Original Text """{text}"""`,
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Mail',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': true,
    },
    isCustom: false,
    order: 2,
  },
  // 3. Explain
  {
    id: 'p_explain',
    title: 'Explain',
    content: 'Explain the following text in clear, simple terms with examples so that anyone can understand:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'FileText',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 3,
  },
  // 4. Summarize (Bullet points)
  {
    id: 'p_summarize_bullet',
    title: 'Summarize',
    content: 'Provide a concise summary of the following text with key bullet points and core takeaways:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'FileCheck',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 4,
  },
  // 5. Translate
  {
    id: 'p_translate',
    title: 'Translate',
    content: 'Translate the following text into natural, idiomatic English (or user target language):',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Languages',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': true,
    },
    isCustom: false,
    order: 5,
  },
  // 6. Improve writing
  {
    id: 'p_improve_writing',
    title: 'Improve writing',
    content: 'Rewrite the following text, which will be delimited by triple quotes, to be more concise and well-written while preserving the original meaning: """${input}""" Provide only the rewritten text as your output, without any quotes or tags. Respond in the same language as the original text.',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Edit3',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': true,
    },
    isCustom: false,
    order: 6,
  },
  // 7. Fix spelling & grammar
  {
    id: 'p_fix_grammar',
    title: 'Fix spelling & grammar',
    content: 'Correct all spelling, punctuation, and grammatical errors while preserving the original tone:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'CheckSquare',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 7,
  },
  // 8. Answer this question
  {
    id: 'p_answer_question',
    title: 'Answer this question',
    content: 'Answer the question directly and comprehensively based on the context and facts provided:',
    category: 'Chat/Ask',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'HelpCircle',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 8,
  },
  // 9. Explain codes
  {
    id: 'p_explain_codes',
    title: 'Explain codes',
    content: 'Explain this code snippet line by line with clear examples and identify any potential bugs or optimizations:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Code',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 9,
  },
  // 10. Find action items
  {
    id: 'p_find_actions',
    title: 'Find action items',
    content: 'Extract all actionable tasks, assignments, deadlines, and follow-ups from the text:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'ListCheck',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 10,
  },
  // 11. Make shorter
  {
    id: 'p_make_shorter',
    title: 'Make shorter',
    content: 'Condense this message into half its current length without losing key facts and clarity:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Minimize2',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 11,
  },
  // 12. Make longer
  {
    id: 'p_make_longer',
    title: 'Make longer',
    content: 'Expand on the following points with more supporting details, context, depth, and examples:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Maximize2',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 12,
  },
  // 13. Simplify language
  {
    id: 'p_simplify_lang',
    title: 'Simplify language',
    content: 'Rewrite the text using plain, simple vocabulary and straightforward sentences:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Type',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 13,
  },
  // 14. Change tone
  {
    id: 'p_change_tone',
    title: 'Change tone',
    content: 'Adjust the tone of this text to be more professional, polite, and persuasive:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Smile',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 14,
  },
  // 15. Brainstorm about...
  {
    id: 'p_brainstorm',
    title: 'Brainstorm about...',
    content: 'Brainstorm creative, unconventional, and actionable ideas for:',
    category: 'Chat/Ask',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Lightbulb',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 15,
  },
  // 16. Outline...
  {
    id: 'p_outline',
    title: 'Outline...',
    content: 'Generate a hierarchical, structured outline with bullet points and subheadings for:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'List',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 16,
  },
  // 17. Blog post...
  {
    id: 'p_blog_post',
    title: 'Blog post...',
    content: 'Write an engaging blog post with catchy subheadings, intro hook, and conclusion for:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'FilePlus',
    showInList: true,
    categoryVisibility: {
      'Chat/Ask': true,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 17,
  },
  // 18. Paragraph about...
  {
    id: 'p_paragraph',
    title: 'Paragraph about...',
    content: 'Write a clear, coherent, and impactful paragraph focused on:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'AlignLeft',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 18,
  },
  // 19. Social media post...
  {
    id: 'p_social_media',
    title: 'Social media post...',
    content: 'Craft an engaging social media post with relevant hashtags and call-to-actions for:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'MessageSquare',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 19,
  },
  // 20. Press release
  {
    id: 'p_press_release',
    title: 'Press release',
    content: 'Draft a formal press release announcing the following update with boilerplate and quote blocks:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Newspaper',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 20,
  },
  // 21. Creative story
  {
    id: 'p_creative_story',
    title: 'Creative story',
    content: 'Write a captivating creative story featuring vivid characters and an immersive plot:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'BookOpen',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 21,
  },
  // 22. To-do list...
  {
    id: 'p_todo_list',
    title: 'To-do list...',
    content: 'Generate a prioritized to-do list with checkboxes and estimated times for:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'CheckSquare',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 22,
  },
  // 23. Meeting agenda...
  {
    id: 'p_meeting_agenda',
    title: 'Meeting agenda...',
    content: 'Create a structured meeting agenda with time allocations, discussion topics, and objectives for:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Calendar',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 23,
  },
  // 24. Sales email...
  {
    id: 'p_sales_email',
    title: 'Sales email...',
    content: 'Write a persuasive, value-driven sales outreach email addressing client pain points:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Mail',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 24,
  },
  // 25. Continue writing
  {
    id: 'p_continue_writing',
    title: 'Continue writing',
    content: 'Seamlessly continue writing from where the text left off, keeping the exact style and tone:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Edit',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': true,
    },
    isCustom: false,
    order: 25,
  },
  // 26. More persuasive
  {
    id: 'p_more_persuasive',
    title: 'More persuasive',
    content: 'Enhance this text to make the argument more compelling, persuasive, and authoritative:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Eye',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 26,
  },
  // 27. Add details
  {
    id: 'p_add_details',
    title: 'Add details',
    content: 'Add supporting details, technical specifications, and background context to enrich this point:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Paperclip',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 27,
  },
  // 28. Add statistics
  {
    id: 'p_add_statistics',
    title: 'Add statistics',
    content: 'Suggest relevant statistical evidence, data points, and numerical context to strengthen:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'BarChart2',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 28,
  },
  // 29. Add humor
  {
    id: 'p_add_humor',
    title: 'Add humor',
    content: 'Inject subtle, clever wit, tasteful irony, and humorous metaphors into:',
    category: 'Writing',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Key',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': false,
      'Writing': false,
    },
    isCustom: false,
    order: 29,
  },
  // 30. More apologetic
  {
    id: 'p_more_apologetic',
    title: 'More apologetic',
    content: 'Rewrite with a sincere, empathetic, respectful, and apologetic tone:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Bell',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 30,
  },
  // 31. More engaging
  {
    id: 'p_more_engaging',
    title: 'More engaging',
    content: 'Make this content significantly more interactive, captivating, and engaging for the audience:',
    category: 'Reading',
    usedIn: ['Chat/Ask', 'Reading', 'Writing'],
    icon: 'Sun',
    showInList: false,
    categoryVisibility: {
      'Chat/Ask': false,
      'Reading': true,
      'Writing': false,
    },
    isCustom: false,
    order: 31,
  },
];
